(() => {
'use strict';
const desktop=document.getElementById('desktop'), startMenu=document.getElementById('start-menu'), taskButtons=document.querySelector('.task-buttons'), clock=document.getElementById('clock');
if(!desktop||!startMenu)return;
const KEY='okenice26:w98:', apps=new Map(), windows=new Map();
let z=1000,seq=0;
const esc=v=>String(v==null?'':v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const stateLoad=()=>{try{return JSON.parse(localStorage.getItem(KEY+'state')||'{}')}catch{return {}}};
const stateSave=o=>localStorage.setItem(KEY+'state',JSON.stringify({...stateLoad(),...o}));
const fs={load(){try{const v=JSON.parse(localStorage.getItem(KEY+'files')||'[]');return Array.isArray(v)?v:[]}catch{return[]}},save(v){localStorage.setItem(KEY+'files',JSON.stringify(v))},add(f){const v=this.load();const x={id:f.id||Date.now()+'',created:Date.now(),updated:Date.now(),...f};v.unshift(x);this.save(v);return x}};
function layer(){let l=document.getElementById('w98-window-layer');if(!l){l=document.createElement('section');l.id='w98-window-layer';desktop.appendChild(l)}return l}
function clockTick(){if(!clock)return;const d=new Date();clock.textContent=d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})} clockTick();setInterval(clockTick,1000);
const themes=['windows-98','windows-95','rainy-day','rose','slate','spruce','desert','brick','eggplant','lilac','maple','marine','plum','pumpkin','storm','teal','wheat'];
function setTheme(t){if(!themes.includes(t))t='windows-98';document.documentElement.dataset.w98Theme=t;localStorage.setItem(KEY+'theme',t)} setTheme(localStorage.getItem(KEY+'theme')||'windows-98');
function taskbar(){if(!taskButtons)return;taskButtons.innerHTML='';windows.forEach(w=>{const b=document.createElement('button');b.className='task-button';b.type='button';b.textContent=w.title;b.title=w.title;b.addEventListener('click',()=>w.el.classList.contains('is-minimized')?restore(w):w.active?minimize(w):focus(w));taskButtons.appendChild(b)})}
function focus(w){windows.forEach(x=>{x.active=false;x.el.classList.remove('is-active')});w.active=true;w.el.classList.add('is-active');w.el.style.zIndex=String(++z);taskbar()}
function minimize(w){w.el.classList.add('is-minimized');w.active=false;taskbar()}
function restore(w){w.el.classList.remove('is-minimized');focus(w)}
function closeWin(w){try{if(w.cleanup)w.cleanup()}catch{}w.el.remove();windows.delete(w.id);taskbar()}
function maximize(w){if(w.el.classList.toggle('is-maximized')){w.prev={left:w.el.style.left,top:w.el.style.top,width:w.el.style.width,height:w.el.style.height};w.el.style.cssText+=';left:0;top:0;width:100%;height:100%'}else if(w.prev)Object.entries(w.prev).forEach(([k,v])=>w.el.style[k]=v);focus(w)}
function drag(w,bar){let d=null;bar.addEventListener('pointerdown',e=>{if(e.target.closest('button')||w.el.classList.contains('is-maximized'))return;const r=w.el.getBoundingClientRect(),dr=desktop.getBoundingClientRect();d={x:e.clientX,y:e.clientY,left:r.left-dr.left,top:r.top-dr.top};bar.setPointerCapture(e.pointerId)});bar.addEventListener('pointermove',e=>{if(!d)return;const dr=desktop.getBoundingClientRect();w.el.style.left=clamp(d.left+e.clientX-d.x,0,Math.max(0,dr.width-w.el.offsetWidth))+'px';w.el.style.top=clamp(d.top+e.clientY-d.y,0,Math.max(0,dr.height-w.el.offsetHeight))+'px'});bar.addEventListener('pointerup',()=>d=null);bar.addEventListener('pointercancel',()=>d=null)}
function resize(w,h){let d=null;h.addEventListener('pointerdown',e=>{if(w.el.classList.contains('is-maximized'))return;e.preventDefault();d={x:e.clientX,y:e.clientY,w:w.el.offsetWidth,h:w.el.offsetHeight};h.setPointerCapture(e.pointerId)});h.addEventListener('pointermove',e=>{if(!d)return;w.el.style.width=clamp(d.w+e.clientX-d.x,240,desktop.clientWidth-4)+'px';w.el.style.height=clamp(d.h+e.clientY-d.y,140,desktop.clientHeight-4)+'px'});h.addEventListener('pointerup',()=>d=null);h.addEventListener('pointercancel',()=>d=null)}
function create(def){const id='w98-'+(++seq),el=document.createElement('article'),ww=def.width||460,hh=def.height||300;el.className='w98-window';el.style.width=ww+'px';el.style.height=hh+'px';el.style.left=clamp(20+windows.size*18,0,Math.max(0,desktop.clientWidth-ww))+'px';el.style.top=clamp(18+windows.size*16,0,Math.max(0,desktop.clientHeight-hh))+'px';el.innerHTML='<div class="w98-titlebar"><span class="w98-title-icon">'+esc(def.icon||'▣')+'</span><span class="w98-title-text">'+esc(def.title)+'</span><span class="w98-title-actions"><button class="w98-win-btn" data-a="min">_</button><button class="w98-win-btn" data-a="max">□</button><button class="w98-win-btn" data-a="close">×</button></span></div><div class="w98-content"></div><div class="w98-resize"></div>';layer().appendChild(el);const w={id,el,title:def.title,active:false,cleanup:null};windows.set(id,w);const bar=el.querySelector('.w98-titlebar');el.querySelector('[data-a="min"]').onclick=()=>minimize(w);el.querySelector('[data-a="max"]').onclick=()=>maximize(w);el.querySelector('[data-a="close"]').onclick=()=>closeWin(w);bar.ondblclick=e=>{if(!e.target.closest('button'))maximize(w)};el.onpointerdown=()=>focus(w);drag(w,bar);resize(w,el.querySelector('.w98-resize'));try{w.cleanup=def.render(el.querySelector('.w98-content'),w)||null}catch(e){el.querySelector('.w98-content').innerHTML='<div class="w98-note"><b>Application error</b><p>'+esc(e.message||e)+'</p></div>'}focus(w);return w}
function reg(d){apps.set(d.id,d)}
function launch(id){return apps.has(id)?create(apps.get(id)):null}
reg({id:'notepad',title:'Notepad',icon:'📝',width:560,height:380,render(r){r.innerHTML='<div class="w98-menubar"><span>File</span><span>Edit</span><span>Search</span><span>Help</span></div><textarea class="w98-notepad-text" spellcheck="false"></textarea><div class="w98-status">Ready</div>';const a=r.querySelector('textarea');a.value=stateLoad().notepadText||'';a.oninput=()=>stateSave({notepadText:a.value})}});
reg({id:'calculator',title:'Calculator',icon:'⌗',width:300,height:300,render(r){r.innerHTML='<div class="w98-calc"><input class="w98-calc-display" value="0" readonly><div class="w98-calc-grid"></div></div>';const d=r.querySelector('input'),g=r.querySelector('.w98-calc-grid'),keys=['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','=','+','C'];let ex='';keys.forEach(k=>{const b=document.createElement('button');b.className='w98-btn';b.textContent=k;g.appendChild(b);b.onclick=()=>{if(k==='C'){ex='';d.value='0';return}if(k==='='){try{d.value=String(Function('return ('+ex.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-')+')')())}catch{d.value='Error'}ex=d.value==='Error'?'':d.value;return}ex+=k;d.value=ex}})}});
reg({id:'explorer',title:'Windows Explorer',icon:'📁',width:620,height:390,render(r){function view(){const f=fs.load();r.innerHTML='<div class="w98-menubar"><span>File</span><span>Edit</span><span>View</span><span>Help</span></div><div class="w98-toolbar"><button class="w98-btn" data-new>New Text File</button><button class="w98-btn" data-refresh>Refresh</button></div><div class="w98-main"><table class="w98-table"><thead><tr><th>Name</th><th>Type</th><th>Modified</th></tr></thead><tbody>'+(f.map(x=>'<tr><td>📄 '+esc(x.name)+'</td><td>'+esc(x.type||'Text Document')+'</td><td>'+new Date(x.updated).toLocaleString()+'</td></tr>').join('')||'<tr><td colspan="3">No user files.</td></tr>')+'</tbody></table></div><div class="w98-status">'+f.length+' file(s)</div>';r.querySelector('[data-refresh]').onclick=view;r.querySelector('[data-new]').onclick=()=>{const n=prompt('File name:','New Text Document.txt');if(n){fs.add({name:n,type:'Text Document',content:''});view()}}}view()}});
reg({id:'paint',title:'Paint',icon:'🎨',width:620,height:430,render(r){r.innerHTML='<div class="w98-toolbar"><button class="w98-btn" data-clear>Clear</button><label> Color <input type="color" value="#000000" data-color></label></div><div style="flex:1;min-height:0;padding:4px"><canvas class="w98-paint-canvas" width="900" height="520"></canvas></div>';const c=r.querySelector('canvas'),x=c.getContext('2d'),col=r.querySelector('[data-color]');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);let down=false;const p=e=>{const b=c.getBoundingClientRect();return{x:(e.clientX-b.left)*c.width/b.width,y:(e.clientY-b.top)*c.height/b.height}};c.onpointerdown=e=>{down=true;c.setPointerCapture(e.pointerId);const q=p(e);x.beginPath();x.moveTo(q.x,q.y)};c.onpointermove=e=>{if(!down)return;const q=p(e);x.strokeStyle=col.value;x.lineWidth=3;x.lineCap='square';x.lineTo(q.x,q.y);x.stroke()};c.onpointerup=c.onpointercancel=()=>down=false;r.querySelector('[data-clear]').onclick=()=>{x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height)}}});
reg({id:'minesweeper',title:'Minesweeper',icon:'💣',width:300,height:310,render(r){r.innerHTML='<div style="padding:8px;display:flex;flex-direction:column;align-items:center;gap:7px"><button class="w98-btn" data-new>New Game</button><span data-status>Ready</span><div class="w98-mine-board"></div></div>';const board=r.querySelector('.w98-mine-board'),status=r.querySelector('[data-status]');function game(){board.innerHTML='';status.textContent='Playing';const W=9,H=9,M=10,all=[...Array(W*H).keys()],set=new Set(all.sort(()=>Math.random()-.5).slice(0,M)),cells=[];const ns=i=>{const X=i%W,Y=Math.floor(i/W),a=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const nx=X+dx,ny=Y+dy;if((dx||dy)&&nx>=0&&nx<W&&ny>=0&&ny<H)a.push(ny*W+nx)}return a};all.forEach(i=>{const b=document.createElement('button');b.className='w98-mine-cell';board.appendChild(b);cells.push(b);b.onclick=()=>{if(set.has(i)){b.textContent='*';b.classList.add('mine');status.textContent='Game over';cells.forEach((c,j)=>{if(set.has(j)){c.textContent='*';c.classList.add('mine')}});return}b.classList.add('revealed');b.textContent=ns(i).filter(n=>set.has(n)).length||'';b.disabled=true}})}r.querySelector('[data-new]').onclick=game;game()}});
reg({id:'internet-explorer',title:'Internet Explorer',icon:'🌐',width:700,height:460,render(r){r.innerHTML='<div class="w98-menubar"><span>File</span><span>Edit</span><span>View</span><span>Favorites</span><span>Help</span></div><div class="w98-toolbar"><input class="w98-input" style="flex:1" value="https://example.com" data-url><button class="w98-btn" data-go>Go</button></div><iframe class="w98-browser-frame" title="Browser" src="https://example.com"></iframe>';const u=r.querySelector('[data-url]'),f=r.querySelector('iframe');r.querySelector('[data-go]').onclick=()=>{try{const a=new URL(u.value);if(!/^https?:$/.test(a.protocol))throw Error();f.src=a.href}catch{alert('Invalid URL')}}}});
reg({id:'sound-recorder',title:'Sound Recorder',icon:'🎙',width:380,height:220,render(r){r.innerHTML='<div class="w98-rec"><p><b>Sound Recorder</b></p><div class="w98-level"><span data-level></span></div><p data-status>Ready.</p><button class="w98-btn" data-record>Record</button> <button class="w98-btn" data-stop disabled>Stop</button></div>';const l=r.querySelector('[data-level]'),s=r.querySelector('[data-status]'),a=r.querySelector('[data-record]'),b=r.querySelector('[data-stop]');let t,p=0;a.onclick=()=>{a.disabled=true;b.disabled=false;s.textContent='Recording…';t=setInterval(()=>{p=(p+9)%100;l.style.width=p+'%'},120)};b.onclick=()=>{clearInterval(t);l.style.width='0';a.disabled=false;b.disabled=true;s.textContent='Recording stopped.'}}});
reg({id:'winamp',title:'Winamp 2.9',icon:'♪',width:360,height:180,render(r){r.innerHTML='<div style="padding:8px;background:#111;color:#0f0;flex:1"><div style="font:bold 18px Arial;color:#fff">WINAMP 2.9</div><div data-state style="margin-top:10px;padding:8px;background:#000">NO FILE PLAYING</div><div style="margin-top:10px;display:flex;gap:4px"><button class="w98-btn" data-play>Play</button><button class="w98-btn" data-stop>Stop</button></div></div>';const s=r.querySelector('[data-state]');r.querySelector('[data-play]').onclick=()=>s.textContent='PLAYING — Retro Mix';r.querySelector('[data-stop]').onclick=()=>s.textContent='STOPPED'}});
reg({id:'help',title:'Windows Help',icon:'❔',width:540,height:360,render(r){r.innerHTML='<div class="w98-menubar"><span>Help</span><span>Index</span><span>Search</span></div><div class="w98-note"><h3>Okenice26 Extended</h3><p>Browser-based Windows 98 desktop recreation.</p><p><b>Double-click</b> desktop shortcuts. <b>Right-click</b> the desktop for context actions. <b>Ctrl+Alt+Delete</b> opens Task Manager.</p><p>User notes and files are stored locally.</p></div>'}});
reg({id:'run',title:'Run',icon:'▶',width:390,height:170,render(r,w){r.innerHTML='<div class="w98-note"><div>Type a program or URL.</div><div style="display:flex;gap:5px;margin-top:8px"><input class="w98-input" style="flex:1" data-cmd value="notepad"><button class="w98-btn" data-ok>OK</button></div></div>';const i=r.querySelector('[data-cmd]'),go=()=>{const c=i.value.trim().toLowerCase();if(apps.has(c)){launch(c);closeWin(w)}else if(/^https?:\/\//.test(c)){window.open(c,'_blank','noopener,noreferrer');closeWin(w)}else alert('Cannot find '+i.value)};r.querySelector('[data-ok]').onclick=go;i.onkeydown=e=>{if(e.key==='Enter')go()}}});
reg({id:'control-panel',title:'Control Panel',icon:'⚙',width:520,height:350,render(r){r.innerHTML='<div class="w98-menubar"><span>View</span><span>Help</span></div><div class="w98-note"><h3>Display</h3><p>Windows color scheme:</p><select class="w98-select" data-theme>'+themes.map(x=>'<option>'+x+'</option>').join('')+'</select><h3>Storage</h3><p>'+fs.load().length+' local file(s).</p><button class="w98-btn" data-reset>Reset local desktop data</button></div>';const s=r.querySelector('[data-theme]');s.value=document.documentElement.dataset.w98Theme;s.onchange=()=>setTheme(s.value);r.querySelector('[data-reset]').onclick=()=>{localStorage.removeItem(KEY+'state');localStorage.removeItem(KEY+'files');location.reload()}}});
reg({id:'ai-assistant',title:'AI Desktop 98',icon:'🤖',width:620,height:420,render(r){r.innerHTML='<div class="w98-menubar"><span>File</span><span>Providers</span><span>Help</span></div><div class="w98-shell"><aside class="w98-sidebar"><button class="active" data-p="chatgpt">ChatGPT</button><button data-p="claude">Claude</button><button data-p="gemini">Gemini</button><button data-p="saved">My Documents</button></aside><main class="w98-main"><div class="w98-panel"><h3>AI Desktop 98</h3><p>Modern AI services inside a Win98 shell.</p><button class="w98-btn" data-open>Open selected provider</button></div><div class="w98-panel" style="margin-top:7px"><textarea class="w98-input" style="width:100%;height:120px;box-sizing:border-box" data-note placeholder="Write a prompt or note…"></textarea><button class="w98-btn" data-save>Save to My Documents</button></div></main></div>';let p='chatgpt';const urls={chatgpt:'https://chatgpt.com/',claude:'https://claude.ai/',gemini:'https://gemini.google.com/app'};r.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{r.querySelectorAll('[data-p]').forEach(x=>x.classList.remove('active'));b.classList.add('active');p=b.dataset.p});r.querySelector('[data-open]').onclick=()=>p==='saved'?launch('explorer'):window.open(urls[p],'_blank','noopener,noreferrer');r.querySelector('[data-save]').onclick=()=>{const n=r.querySelector('[data-note]');if(n.value.trim()){fs.add({name:'AI Note '+Date.now()+'.txt',type:'Text Document',content:n.value});n.value=''}}}});
reg({id:'about',title:'About Okenice26',icon:'ⓘ',width:430,height:280,render(r){r.innerHTML='<div class="w98-note"><h2>Okenice26 Extended</h2><p>Macroloft Luxffery 26 — Windows 98 recreation.</p><p>Working desktop shell, windows, local files, classic utilities, themes, keyboard shortcuts and AI service launchers.</p><p>Build: Extended 1.0</p></div>'}});
reg({id:'task-manager',title:'Task Manager',icon:'▤',width:520,height:330,render(r){r.innerHTML='<div class="w98-menubar"><span>File</span><span>Options</span><span>View</span></div><div class="w98-main"><table class="w98-table"><thead><tr><th>Application</th><th>Status</th></tr></thead><tbody>'+[...windows.values()].map(x=>'<tr><td>'+esc(x.title)+'</td><td>Running</td></tr>').join('')+'</tbody></table></div><div class="w98-status">'+windows.size+' window(s)</div>'}});
function addStart(){if(startMenu.querySelector('.w98-start-extra'))return;const box=document.createElement('div');box.className='w98-start-extra';[['notepad','📝','Notepad'],['calculator','⌗','Calculator'],['paint','🎨','Paint'],['minesweeper','💣','Minesweeper'],['explorer','📁','Windows Explorer'],['ai-assistant','🤖','AI Desktop 98'],['control-panel','⚙','Control Panel']].forEach(x=>{const b=document.createElement('button');b.type='button';b.innerHTML='<span class="w98-mini-icon">'+x[1]+'</span><span>'+x[2]+'</span>';b.onclick=()=>{startMenu.hidden=true;launch(x[0])};box.appendChild(b)});startMenu.querySelector('.start-items')?.appendChild(box)}
function patchStart(){startMenu.querySelectorAll('.start-item').forEach(b=>{const t=b.textContent.replace(/▶/g,'').trim().toLowerCase();if(t.includes('help'))b.addEventListener('click',()=>{startMenu.hidden=true;launch('help')});if(t.includes('run'))b.addEventListener('click',()=>{startMenu.hidden=true;launch('run')});if(t.includes('shut down'))b.addEventListener('click',()=>{startMenu.hidden=true;shutdown()})})}
function shutdown(){const l=document.createElement('div');l.className='w98-shutdown-layer';l.innerHTML='<div class="panel"><div class="title">Shut Down Windows</div><div class="body"><b>What do you want the computer to do?</b><p>Classic shutdown simulation.</p></div><div class="actions"><button class="w98-btn" data-c>Cancel</button><button class="w98-btn" data-s>Shut Down</button></div></div>';desktop.appendChild(l);l.querySelector('[data-c]').onclick=()=>l.remove();l.querySelector('[data-s]').onclick=()=>{l.innerHTML='<div>It is now safe to turn off your computer.</div>'}}
function context(){const m=document.getElementById('context-menu');if(!m)return;m.querySelector('[data-context="refresh"]')?.addEventListener('click',()=>location.reload());m.querySelector('[data-context="properties"]')?.addEventListener('click',()=>launch('control-panel'));m.querySelector('[data-context="new"]')?.addEventListener('click',()=>launch('notepad'))}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.altKey&&e.key==='Delete'){e.preventDefault();launch('task-manager')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();launch('notepad')}if(e.key==='Escape')startMenu.hidden=true});
document.addEventListener('dblclick',e=>{const icon=e.target.closest('#desktop-icons .desktop-icon[data-shortcut-id]');if(!icon)return;const item=window.__OKENICE_CATALOG__&&window.__OKENICE_CATALOG__.get(icon.dataset.shortcutId);if(item&&item.type==='app'){e.preventDefault();const w=launch('internet-explorer');if(w){const u=w.el.querySelector('[data-url]'),go=w.el.querySelector('[data-go]');u.value=item.url;go.click()}}},true);
addStart();patchStart();context();
window.__OKENICE_W98__={launch,apps,windows,fs,setTheme};
})();